"""Attach the NegoLog agents' private RNGs to NegMAS's global seed.

NegMAS's `seed_all` seeds the global generators of :mod:`random` and
:mod:`numpy.random`, which covers most of this package. It does not reach the
fourteen ``random.Random()`` instances the vendored NegoLog agents build for
themselves: constructed with no argument, each one seeds from OS entropy and so
ignores any amount of module-level seeding. Some are agent attributes
(``NiceTitForTat``, ``HardHeaded``, ``SAGA``, ...) and some are built inside a
method on every call (``AgentGG``, ``Atlas3``, ``CUHKAgent``), so there is no
object to reach in after the fact -- the constructor itself has to change.

`install` therefore registers a seeder that swaps in a `random.Random` subclass
supplying a derived seed when the caller gives none. The swap happens only when
NegMAS actually applies a seed, so with ``NEGMAS_RAND_SEED`` unset nothing is
patched and every agent draws fresh entropy exactly as it did before.

The vendored agents are regenerated by ``scripts/update_vendor.sh``, so fixing
their call sites in place is not an option.
"""

from __future__ import annotations

import itertools
import random

try:
    from negmas.helpers.rand import register_seeder
except ImportError:  # negmas too old; nothing to hook onto
    register_seeder = None  # type: ignore[assignment]

__all__ = ["install"]

_Random = random.Random
"""The real class, captured before any patching so installing twice is a no-op"""

_seed = 0
"""The seed in effect, mixed into every seed this module derives"""

_counter = itertools.count()
"""Makes each derived seed distinct: two RNGs must not share a stream"""


class _SeededRandom(_Random):
    """A `random.Random` that seeds itself when the caller supplies no seed.

    An explicit seed is always honoured, so ``random.Random(42)`` elsewhere in
    the process keeps meaning exactly what it did.
    """

    def __init__(self, *args, **kwargs):
        if args or "x" in kwargs:
            super().__init__(*args, **kwargs)
        else:
            # Plain integer arithmetic, so the derived seed is reproducible and
            # unique per instance. Python 3.14 only accepts int/float/str/bytes
            # seeds, which rules out hashing a (seed, count) tuple.
            super().__init__(_seed * 2**32 + next(_counter))


def _seeder(seed: int) -> None:
    """Make every later unseeded `random.Random()` reproducible from `seed`."""
    global _seed, _counter
    _seed, _counter = seed, itertools.count()
    random.Random = _SeededRandom  # type: ignore[misc]


def install() -> None:
    """Hook this package's private RNGs onto NegMAS's global seed.

    Called once when :mod:`negmas_negolog` is imported. Best-effort: an older
    NegMAS with no `register_seeder`, or any failure to register, leaves the
    package working exactly as it does unseeded.
    """
    if register_seeder is None:
        return

    def seeder(seed: int) -> None:
        try:
            _seeder(seed)
        except Exception:  # a seeder must never take the run down
            pass

    try:
        register_seeder(seeder)
    except Exception:
        pass
